# TODO This resource should be created condidionally based on the provider or only the part of the provider should be created conditionally
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-aws # TODO Rename this dynamically
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-external-secrets
            namespace: {{ .Release.Namespace }}
