---
{{- if .Values.cluster_secret_stores.k8s -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.cluster_secret_stores.k8s.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    kubernetes:
      # We decided that the K8s secrets reside in the same namespace as the External Secrets Operator.
      remoteNamespace: {{ .Release.Namespace }}
      server: https://kubernetes.default.svc
      caProvider:
        secret:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
{{- end -}}
