= devops-stack-module-secrets
// Document attributes to replace along the document
:external-secrets-chart-version: 0.10.0
:reloader-chart-version: 1.0.119
:external-secrets-original-repo-url: https://github.com/external-secrets/external-secrets
:reloader-original-repo-url: https://github.com/stakater/Reloader

A https://devops-stack.io[DevOps Stack] module to deploy the https://external-secrets.io/v{external-secrets-chart-version}/[External Secrets Operator] and {reloader-original-repo-url}[Reloader].

The charts used by this module is shipped in this repository as well, in order to avoid any unwanted behaviors caused by unsupported versions. 

[cols="1,1,1,1",options="autowidth,header"]
|===
|Chart |Current Chart Version |Original Repository |Default Values
|*External Secrets Operator* |*{external-secrets-chart-version}* |{external-secrets-original-repo-url}/tree/main/deploy/charts/external-secrets[Chart] |https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets/{external-secrets-chart-version}?modal=values[`values.yaml`]
|*Reloader* |*{reloader-chart-version}* |{reloader-original-repo-url}tree/master/deployments/kubernetes/chart/reloader[Chart] |https://artifacthub.io/packages/helm/stakater/reloader/{reloader-chart-version}?modal=values[`values.yaml`]
|===

[WARNING]
====
The variants of the module contained on the subfolders `aws_secrets_manager`, `azure_key_vault` and `k8s_secrets` are not fully developed yet. They are a work in progress to properly manage the secrets for all the DevOps Stack modules themselves.

Consequently, only the root module is meant to be used at the moment. This will allow you to have an External Secrets Operator and Reloader deployed on your cluster which you can then used by adding the necessary manifests and annotations to your clusters.

// TODO From below here

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,terraform]
----
module "secrets" {
  source = "git::https://github.com/camptocamp/devops-stack-module-secrets.git?ref=<RELEASE>"

  cluster_name   = module.sks.cluster_name
  base_domain    = module.sks.base_domain
  argocd_project = module.sks.cluster_name

  dependency_ids = {
    argocd = module.argocd.id
  }
}
----

== Technical Reference

=== Dependencies

==== `module.argocd.id`

Obviously, the module depends on an already running Argo CD in the cluster in order for the application to be created.

// BEGIN_TF_DOCS
// END_TF_DOCS

=== Reference in table format 

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
// END_TF_TABLES
====
